### ISSUE TITLE
panic: runtime error: index out of range [1] with length 0

### ISSUE THREAD

**Issue by hao-lh** [owen-gxz/douyin_download#3]
Hi there,

Recently days the released binary file seemed suffering from following issues, already tried different urls and the same issue happened, could you help look at this issue?
Also attached diagnostics information for your debug purpose, thanks.

panic: runtime error: index out of range [1] with length 0

goroutine 1 [running]:
github.com/owen-gxz/douyin_download.GetDouyinInfo(0xc00012c140, 0x1d, 0x1d)
	/home/owen/go/src/github.com/owen-gxz/douyin_download/download.go:36 +0x1bd
main.main()
	/home/owen/go/src/github.com/owen-gxz/douyin_download/cmd/main.go:21 +0x2ba

**Comment by owen-gxz** [comment]
I'm a little busy these days. Have you solved it?

**Comment by hao-lh** [comment]
I retired this, and magically recovered.
Thought might be interface change on remote site?

**Comment by owen-gxz** [comment]
ok
